### ISSUE TITLE
ReferenceError: require not defined in the admin section

### ISSUE THREAD

**Issue by rebborodin** [ether/etherpad-require-kernel#2]
hello,

I am working with the following plugins on the etherpad: 'ep_user_pad' and 'ep_user_pad_frontend'.
Now, visiting https:/myExample.com/admin/userpadadmin/, brings me to the above mentioned error. 

![erro_screen](https://cloud.githubusercontent.com/assets/12681316/9069604/8e9a8162-3aea-11e5-8763-9f55dd0c8d54.png)

Any clue?

**Comment by rebborodin** [comment]
I noticed that there is no file called 'require-kernel.js' ???

**Comment by JohnMcLear** [comment]
Do you get these errors without the plugins?

**Comment by rebborodin** [comment]
no, but it is connected with this [issue](https://github.com/aoberegg/ep_user_pad/issues/11)
is there a chance the etherpad-lite require.js was somehow changed, when etherpad was being upgrading 1.4.1 to 1.5.0?
ep_user_pad_frontend is an old feature, which wasn't update since 14. Feb 2014, but it was working in the begining of the year.

Thanks

**Comment by JohnMcLear** [comment]
possibly, dig into it using bisect.

**Comment by rhansen** [comment]
Closing as stale.
